apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'mysql-server'
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
         app: mysql
    spec:
      containers:
      - image: mysql:5.7.28
        name: mysql
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD 
          value: password
        - name: MYSQL_DATABASE
          value: hamus
        - name: d_host
          value: mysql-service
        # volumeMounts:
        # - mountPath: /var/lib/mysql
        #   name: mysql-data
        

