kind: Service
apiVersion: v1
metadata:
  name: 'myserver-service'
  labels:
    app: my-server
spec:
  type: LoadBalancer
  selector:
    app: my-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
